name: dart_kit
description: A lightweight Dart utility package offering common abstractions and missing features to write safer, more expressive code.
version: 1.0.0
homepage: https://github.com/maranix/dart_kit
repository: https://github.com/maranix/dart_kit
issues: https://github.com/maranix/dart_kit/issues

topics:
  - functional
  - option
  - result
  - either
  - fp

environment:
  sdk: ^3.10.0

dependencies:
  equatable: ^2.0.8
  meta: ^1.17.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
