name: daxle_flutter
description: A lightweight Flutter utility package based on daxle, offering common abstractions and missing features to write safer, more expressive code.
version: 1.0.0
homepage: https://github.com/maranix/daxle/tree/main/packages/daxle_flutter
repository: https://github.com/maranix/daxle/tree/main/packages/daxle_flutter
issues: https://github.com/maranix/daxle/issues?q=state%3Aopen%20label%3Adaxle_flutter

topics: 
  - flutter
  - daxle
  - viewmodel
  - reactive
  - extensions

environment:
  sdk: ^3.10.7
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  daxle: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: ^1.26.3
